import type { Metadata } from "next";
// --- FIX: Import from the 'geist' package ---
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
// --- END FIX ---
import "./globals.css";
import Footer from "./pages/Footer";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";
import { Navbar } from "./pages/Navbar";
import { AuthProvider } from "./pages/auth/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // --- FIX: Use the imported objects directly ---
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased flex flex-col min-h-screen`}
        // --- END FIX ---
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <AuthProvider>
            <Toaster />
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
